version: '3'

services:
  keycloakdb:
    image: postgres:13.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - carbon
  keycloak:
    image: jboss/keycloak:${KEYCLOAK_VERSION}
    depends_on:
      - keycloakdb
    environment:
      - DB_VENDOR=postgres
      - DB_ADDR=keycloakdb
      - DB_DATABASE=${POSTGRESQL_DB}
      - DB_USER=${POSTGRESQL_USER}
      - DB_PASSWORD=${POSTGRESQL_PASS}
      - KEYCLOAK_USER=${KEYCLOAK_USER}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
      - JAVA_OPTS=-Djboss.as.threads.maxThreads=100 -Djboss.as.threads.queueLength=500
      - KEYCLOAK_FRONTEND_URL=https://${TRAEFIK_PREFIX}${DOMAIN}/auth
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${TRAEFIK_PREFIX}.entrypoints=https"
      - "traefik.http.routers.${TRAEFIK_PREFIX}.rule=Host(`${TRAEFIK_PREFIX}${DOMAIN}`)"
      - "traefik.http.routers.${TRAEFIK_PREFIX}.tls=true"
      - "traefik.http.routers.${TRAEFIK_PREFIX}.service=${TRAEFIK_PREFIX}"
      - "traefik.http.services.${TRAEFIK_PREFIX}.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    networks:
      - carbon

networks:
  carbon:
    external: true
  local-keycloak: