version: "2.3"
volumes:
  jira-data:
  jira-postgres:
  jira-data-backups:
  jira-postgres-backups:
  traefik-certificates:

services:
  postgres:
    # Image tag (replace with yours)
    image: postgres:11.11
    volumes:
      - jira-postgres:/var/lib/postgresql/data
    environment:
      # Database name (replace with yours)
      POSTGRES_DB: jiradb
      # Database user (replace with yours)
      POSTGRES_USER: postgres
      # Database password (replace with yours)
      POSTGRES_PASSWORD: servicemode
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h 127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  jira:
    # Image tag (replace with yours)
    image: atlassian/jira-software:8.16-jdk11
    volumes:
      - jira-data:/var/atlassian/application-data/jira
    environment:
      # Application memory (replace with yours)
      JVM_MINIMUM_MEMORY: 8G
      JVM_MAXIMUM_MEMORY: 8G
      # Jira URL (replace with yours)
      ATL_PROXY_NAME: ${DOMAIN}
      ATL_PROXY_PORT: 443
      ATL_TOMCAT_SCHEME: https
      ATL_TOMCAT_SECURE: 'true'
      ATL_JDBC_URL=jdbc: postgresql://localhost:5432/jiradb
      ATL_JDBC_USER: postgres
      ATL_JDBC_PASSWORD: servicemode
      ATL_DB_DRIVER: org.postgresql.Driver
      # опция для сброса пароля администратора
      #JVM_SUPPORT_RECOMMENDED_ARGS: "-Datlassian.recovery.password=servicemode"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    labels:
      - "traefik.enable=true"
      # Jira URL (replace with yours)
      - "traefik.http.routers.${TRAEFIK_PREFIX}.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.${TRAEFIK_PREFIX}.service=${TRAEFIK_PREFIX}"
      - "traefik.http.routers.${TRAEFIK_PREFIX}.entrypoints=https"
      - "traefik.http.services.${TRAEFIK_PREFIX}.loadbalancer.server.port=8080"
      - "traefik.http.routers.${TRAEFIK_PREFIX}.tls=true"
      - "traefik.http.services.${TRAEFIK_PREFIX}.loadbalancer.passhostheader=true"
      - "traefik.http.routers.${TRAEFIK_PREFIX}.middlewares=compresstraefik"
      - "traefik.http.middlewares.compresstraefik.compress=true"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      carbon:

  backups:
    # Image tag (replace with yours)
    image: postgres:11.11
    # Database backups prune interval (replace with yours). Default is 7 days.
    # find /srv/jira-postgres/backups -type f -mtime +7 | xargs rm -f

    # Application data backups prune interval (replace with yours). Default is 7 days.
    # find /srv/jira-application-data/backups -type f -mtime +7 | xargs rm -f

    # Jira backups interval (replace with yours). Default is 1 day.
    # sleep 24h

    # Run jira-restore-application-data.sh to restore application data if needed.
    # Run jira-restore-database.sh to restore database if needed.
    command: sh -c 'sleep 30m
             && while true; do
             PGPASSWORD="$$(echo $$POSTGRES_PASSWORD)"
             pg_dump
             -h postgres
             -p 5432
             -d jiradb
             -U postgres | gzip > /srv/jira-postgres/backups/jira-postgres-backup-$$(date "+%Y-%m-%d_%H-%M").gz
             && tar -zcpf /srv/jira-application-data/backups/jira-application-data-backup-$$(date "+%Y-%m-%d_%H-%M").tar.gz /var/atlassian/application-data/jira
             && find /srv/jira-postgres/backups -type f -mtime +7 | xargs rm -f
             && find /srv/jira-application-data/backups -type f -mtime +7 | xargs rm -f;
             sleep 24h; done'
    volumes:
      - jira-data:/var/atlassian/application-data/jira
      # Application data backups location
      - jira-data-backups:/srv/jira-application-data/backups
      # Database backups location
      - jira-postgres-backups:/srv/jira-postgres/backups
    environment:
      # Database password (replace with yours)
      POSTGRES_PASSWORD: servicemode
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      jira:
        condition: service_healthy
networks:
  carbon:
    external: true

